### ISSUE TITLE
i  use your  winio4j  it can be run at win10 , how can i run  it on win 7 64 bit

### ISSUE THREAD

**Issue by wzskyline** [supermoonie/winio4J#3]
您好， 这个项目如何才能再win7 中运行成功。 在win7上测试  代码不会报错  就是不会同win10 环境中 打印字母

**Comment by supermoonie** [comment]
你的win 7是笔记本还是台式机？台式机需要PS/2接口键盘的

**Comment by wzskyline** [comment]
电脑win7 笔记本有成功案例，台式机机顶盒子那种，服务能安装上，可能就是接口不对，如何确认那个 接口键盘类型哦

**Comment by supermoonie** [comment]
圆孔键盘就是那种接口

发自我的 iPhone
