### ISSUE TITLE
这个 可以改写成 nodejs 的版本吗

### ISSUE THREAD

**Issue by wzskyline** [supermoonie/winio4J#4]
系统位操作的内容  感觉工程量很大。

**Comment by supermoonie** [comment]
可以改写成nodejs 版本，node中有 ffi 模块可以调用dll，只不过我对nodejs 的语法并不熟悉，非常抱歉。

**Comment by wzskyline** [comment]
嗯知道这个模块，就是除了写位偏移指令的map映射表，不知道还需要封装哪些函数。得沿着的您作品开始构建了😂------------------ 原始邮件 ------------------
发件人: "supermoonie"<notifications@github.com>
发送时间: 2019年6月7日(星期五) 晚上9:19
收件人: "supermoonie/winio4J"<winio4J@noreply.github.com>;
抄送: "wzskyline"<wzskyline@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [supermoonie/winio4J] 这个 可以改写成 nodejs 的版本吗 (#4)



可以改写成nodejs 版本，node中有 ffi 模块可以调用dll，只不过我对nodejs 的语法并不熟悉，非常抱歉。
 
&mdash;

**Comment by supermoonie** [comment]
主要是映射WinIo.java 里的那些函数，具体可参考 WinIo.chm

**Comment by wzskyline** [comment]
嗨，
后来有简单看过 HID 驱动 也就是USB 键盘接口的 模拟按键 
简单找了点 USB 发送数据的格式 但是没有找到会发送到哪个端口
https://blog.csdn.net/luohsh1/article/details/8645471 
想 能 在一些没有PS/2键盘接口的电脑上按下简单字符
可以方便加个QQ吗

**Comment by supermoonie** [comment]
QQ: 81194365




在 2019-06-14 14:16:11，"wzskyline" <notifications@github.com> 写道：
嗨，
后来有简单看过 HID 驱动 也就是USB 键盘接口的 模拟按键
简单找了点 USB 发送数据的格式 但是没有找到会发送到哪个端口
https://blog.csdn.net/luohsh1/article/details/8645471
想 能 在一些没有PS/2键盘接口的电脑上按下简单字符
可以方便加个QQ吗
